config/routes.rb
Rails.application.routes.draw do
  resources :coins
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
################################################################################
# Model:  Coin
#
# Purpose:
#
# Coin attributes:
#   name      - string,  not NULL, unique
#   code      - string,  not NULL, unique
#   kind      - enum { crypto (0) | fiat (1) }
#   unicode   - string
#   status    - enum { active (0) | archived (1) }
#
#  16.04.2022 ZT
################################################################################
class Coin < ApplicationRecord
  include ImagesHandleable

  has_many :coin_nicknames, dependent: :delete_all
  has_many :based_pairs,  class_name: 'Pair', foreign_key: 'base_id',  dependent: :delete_all
  has_many :quoted_pairs, class_name: 'Pair', foreign_key: 'quote_id', dependent: :delete_all
 
  has_one_attached :cover_image, dependent: :destroy

  enum kind:   %w(crypto fiat)
  enum status: %w(active archived)

  validates :name,  presence: true, uniqueness: true
  validates :code,  presence: true, uniqueness: true
end
  

app/models/concerns/images_handleable.rb
################################################################################
#   ActiveStorage images are handled here
################################################################################
module ImagesHandleable
  extend ActiveSupport::Concern

  included do
    has_one_attached  :cover_image
    has_many_attached :images
    before_destroy    :remove_all_images, prepend: true

    attr_accessor     :remove_cover_image
  end

  # Removes all images (if any) for destroyed instance 
  def remove_all_images
    self.cover_image.purge                 if self.cover_image.attached?
    self.images.each {|image| image.purge} if self.images.attached?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # http_basic_authenticate_with(name: Rails.application.credentials.config[:http][:name], password: Rails.application.credentials.config[:http][:password]) if ACCESS_RESTRICTED
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  
  def index
    @coins = Coin.all.order(:id)
  end

  def show
  end

  def new
    @coin = Coin.new
  end

  def edit
  end

  def create
    @coin = Coin.new(coin_params)

    if @coin.save
      redirect_to @coin, notice: "Coin was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @coin.update(coin_params)
      redirect_to @coin, notice: "Coin was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @coin.destroy
    redirect_to coins_url, notice: "Coin was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:name, :code, :kind, :unicode, :status, :cover_image, :remove_cover_image, images: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_name
    Rails.application.class.module_parent
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
  <div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full">
            <tbody>
              <% visible_attributes = @coin.attributes.reject {|k, v| k == "password_digest" or k == "created_at" or k == "updated_at"} %>
              <% visible_attributes.each_with_index do |(key, value), index| %>
                <% if index.even? %>
                  <tr class="bg-gray-100 border-b">
                <% else %>
                  <tr class="bg-white border-b">
                <% end %>
                  <td><%= key.capitalize %></td>
                  <td class="font-mono"><%= value %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= render 'shared/show_images', object: @coin %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin, class: "contents") do |form| %>
  <% if coin.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(coin.errors.count, "error") %> prohibited this coin from being saved:</h2>

      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-col mb-4">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex flex-col mb-4">
    <%= form.label :code %>
    <%= form.text_field :code, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex flex-col mb-4">
    <%= form.label :kind %>
    <%= form.select :kind, options_for_select(Coin.kinds.map {|key, value| [key.titleize, Coin.kinds.key(value)]}, @coin.kind), class: "form-select mt-1 block w-full" %>
  </div>

  <div class="flex flex-col mb-4">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Coin.statuses.map {|key, value| [key.titleize, Coin.statuses.key(value)]}, @coin.status), class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="flex flex-col mb-4">
    <%= form.label :cover_image %>
    <%= form.file_field :cover_image %>
  </div>

  <%= render 'shared/form_images', f: form, object: coin %>

  <div class="inline">
    <%= form.submit "Save", class: "rounded-lg py-3 px-3 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/coins/edit.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">Editing coin</h1>

  <%= render "form", coin: @coin %>
  <br>
  <%= link_to "Show", @coin, class: "rounded-lg py-1 px-2 text-blue-500 bg-blue-100 inline-block font-medium" %>
  <%= link_to "To List", coins_path, class: "rounded-lg py-1 px-2 text-gray-500 bg-gray-300 inline-block font-medium" %>
</div>

app/views/coins/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Coins</h1>
    <%= link_to "New coin", new_coin_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  
  <% if @coins.present? %>
    <div class="flex flex-col">
      <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 inline-block min-w-full sm:px-6 lg:px-8">
          <div class="overflow-hidden">
            <table class="min-w-full bg-white">
              <thead class="bg-gray-300">
                <tr>
                  <% @coins.first.attributes.each do |key, value| %>
                    <% unless key == "created_at" or key == "updated_at" %>
                      <th scope="col" class="text-base font-bold text-gray-900 px-6 py-4 text-left">
                        <%= "#{key.titleize}" %>
                      </th>
                    <% end%>
                  <% end %>
                  <% if Coin.reflect_on_attachment(:cover_image).present? %>
                    <th scope="col" class="text-base font-bold text-gray-900 px-6 py-4 text-left">
                      Cover
                    </th>
                  <% end %>
                  <th class="text-base font-bold text-gray-900 px-6 py-4 text-left">Actions</th>
                </tr>
              </thead>

              <tbody>
                <% @coins.each do |coin| %>
                  <% if coin.id.even? %>
                    <tr class="bg-gray-100 border-b">
                  <% else %>
                    <tr class="bg-white border-b">
                  <% end %>
                    <% coin.attributes.each do |key, value| %>
                      <% unless key == "created_at" || key == "updated_at" %>
                        <% if key == "status" %>
                          <% if coin.active? %>
                            <td class="text-sm text-green-500 font-light px-6 py-4 whitespace-nowrap">
                          <% else %>
                            <td class="text-sm text-red-800 font-light px-6 py-4 whitespace-nowrap">
                          <% end %>
                              <%= value %>
                            </td>    
                        <% else %>
                          <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                            <%= value %>
                          </td>
                        <% end %>
                      <% end %>
                    <% end %>
                    <% if Coin.reflect_on_attachment(:cover_image).present? %>
                      <td  class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                        <% if coin.cover_image.attached? %>
                          <%= image_tag coin.cover_image.variant(resize_to_limit: [30, 30]) %>
                        <% end %>
                      </td>
                    <% end %>
                    <td>
                      <%= link_to "Show", coin, class: "rounded-lg py-1 px-2 text-blue-500 bg-blue-100 inline-block font-medium" %>
                      <%= link_to "Edit", edit_coin_path(coin), class: "rounded-lg py-1 px-2 text-yellow-500 bg-yellow-100 inline-block font-bold" %>
                      <%= link_to "Destroy", coin, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "rounded-lg py-1 px-2 text-red-500 bg-red-100 font-medium" %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/coins/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">New coin</h1>

  <%= render "form", coin: @coin %>
  <br>
  <%= link_to "To List", coins_path, class: "rounded-lg py-1 px-2 text-gray-500 bg-gray-300 inline-block font-medium" %>
</div>

app/views/coins/show.html.erb
<div class="w-full">
  <p style="color: green"><%= notice %></p>

  <h1 class="font-bold text-4xl">Coin</h1>
  <%= render @coin %>

  <%= link_to "Edit", edit_coin_path(@coin), class: "rounded-lg py-1 px-2 text-yellow-500 bg-yellow-100 inline-block font-bold" %>
  <%= link_to "To List", coins_path, class: "rounded-lg py-1 px-2 text-blue-500 bg-blue-100 inline-block font-medium" %>
  <%= link_to "Destroy", @coin, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "rounded-lg py-1 px-2 text-red-500 bg-red-100 font-medium" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div>
  <h1 class="font-bold text-4xl">Pages#home</h1>
  <p>Find me in app/views/pages/home.html.erb</p>
</div>

app/views/shared/_debug.html.erb
<div class="text-center p-6 bg-gray-200">
  <%= debug params %>

  <% unless @current_user.nil? %>
    <%= debug "current_user: #{@current_user.full_name}; current_role: #{@current_user.role}" %>
  <% end %>

  <%= debug "Versions: #{RUBY_ENGINE}-#{RUBY_VERSION}-p#{RUBY_PATCHLEVEL} | Rails: #{Rails.version}" %>

  <% if GIT_BRANCH.present? %>
    <%= debug "Git branch: #{GIT_BRANCH}; Commit: #{GIT_COMMIT} (#{l GIT_COMMIT_TIMESTAMP, format: '%d.%m.%Y %H:%M'})" %>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="my-5 text-center lg:text-left bg-gray-100 text-gray-600">
  <div class="flex items-center justify-center p-7">
    <%= image_tag("logos/ZT_Lab.gif", size: "32x32") + "© #{Time.now.year}" %>
  </div>
  <%= render 'shared/debug' if ZT_DEBUG %>

</footer>

app/views/shared/_form_images.html.erb
<% if object.class.name.constantize.reflect_on_attachment(:cover_image).present? %>
  <hr/>
  <div class="flex flex-col mb-4">
    <%= f.label "Cover Image" %>
    <%= f.file_field :cover_image %>
  </div>

  <br/>
  <div class="row">
    <% if object.cover_image.attached? %>
      <div class="col-md-2">
        <%= image_tag object.cover_image.variant(resize_to_fit: [100, 100]) %>
        <%= f.check_box :remove_cover_image %>
      </div>
      <div class="col-md-2">
        
        <i class="fas fa-trash"></i>
      </div>
    <% end %>
  </div>
<% end %>
<% if object.class.name.constantize.reflect_on_attachment(:images).present? %>
  <hr/>
  <div class="row">
    <div class="col-md-4">
      <%= f.label t 'images.gallery' %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <%= f.file_field :images, multiple: true %>
    </div>
  </div>
  <br/>
  <div class="row">
    <% if object.images.attached? %>
      <% object.images.each do |image| %>
        <div class="col-md-3 form-image-cell">
          <%= image_tag image.variant(resize_to_fit: [100, 100]) %>
          <%= check_box_tag 'image_to_remove_ids[]', image.id %>
          <i class="fas fa-trash"></i>
        </div>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
  <nav class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-800">
    <div class="container flex flex-wrap justify-between items-center mx-auto">
      <%= link_to image_tag('logos/app.png', title: "#{app_name}",  size: '53x30'), root_path %>
      <button data-collapse-toggle="mobile-menu" type="button" class="inline-flex items-center p-2 ml-3 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="mobile-menu" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z" clip-rule="evenodd"></path></svg>
        <svg class="hidden w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>

      <div class="hidden w-full md:block md:w-auto" id="mobile-menu">
        <ul class="flex flex-col mt-4 md:flex-row md:space-x-8 md:mt-0 md:text-sm md:font-medium">
          <li >
            <%= link_to "Coins", coins_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Add Trades", trades_index_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Create Cash", trades_create_cash_path, data: { confirm: 'Are you sure?' },  class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Update Cash", trades_update_cash_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Candlesticks", trades_candlesticks_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Order Book", trades_order_book_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Runs", runs_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Selections", selections_new_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Ticks", trades_tick_charts_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Candles", candles_add_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "Patterns", patterns_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
          <li>
            <%#= link_to "PatRec", patrec_doji_path, class: "block py-2 pr-4 pl-3 text-gray-700 border-b border-gray-100 hover:bg-gray-50 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-gray-400 md:dark:hover:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_show_images.html.erb
<% if object.class.name.constantize.reflect_on_attachment(:cover_image).present?  %>
  <table class="min-w-full">
    <tbody>
      <tr class="bg-blue-100 border-b">
        <td><%= "Cover Image" %><td>
          <% if object.cover_image.attached? %>
            <%= image_tag object.cover_image.variant(resize_to_limit: [40, 40]) %>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
<% end %>
<% if object.class.name.constantize.reflect_on_attachment(:images).present? and object.images.attached? %>
  <table class="min-w-full">
    <tbody>
      <tr>
        <td><%= "Images Gallery" %><td>
        <% object.images.each do |image| %>
          <td>
            <%= image_tag image.variant(resize_to_limit: [50, 50]) %>
          </td>
        <% end %>
      </tr>
    </tbody>
  </table>
<% end %>